# run this file as: 'docker compose up'
services:
  api:
    build:
      context: .
    environment:
      - MYSQL_USER=root
      - MYSQL_PWD=password

    ports:
      - 5500:5500

    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    restart: unless-stopped
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./database/schema/queries.sql:/docker-entrypoint-initdb.d/0_queries.sql
      - db-data:/var/lib/msql
    environment:
      - MYSQL_DATABASE=burger_app
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 3
volumes:
  db-data:
