# run this file as: 'docker compose up'
services:
  api:
    build:
      context: .
    environment:
      - MYSQL_USER=root
      - MYSQL_PWD=password

    ports:
      - 5500:5500

    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.3
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./database/schema/script.sql:/docker-entrypoint-initdb.d/0_script.sql
      - db-data:/var/lib/msql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=burger_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  db-data:
