# 'docker compose down -v'
# 'docker compose up --force-recreate'
# creates dockerized mysql container with populated db burger_app

services:
  db:
    image: mysql:8.3
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./database/schema/script.sql:/docker-entrypoint-initdb.d/0_script.sql
      - db-data:/var/lib/msql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
      - MYSQL_DATABASE=${MYSQL_DB}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  db-data:
